# Generated by Django 6.0.6 on 2026-06-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('APPLICANT', 'Applicant'), ('REVIEWER', 'Reviewer')], default='APPLICANT', max_length=20),
        ),
    ]
